module.exports = {
    chamber: "upper",
    crp_id: "N00003028",
    cspan_id: "45516",
    current_office_index: 0,
    current_party: "R",
    displayName: "Testing Name",
    end_date: "2021-01-03",
    first_name: "Testing",
    govtrack_id: "400004",
    icpsr_id: "29701",
    id: "test_id",
    in_office: true,
    last_name: "Name",
    last_updated: "2019-11-18 01:00:54 -0500",
    member_id: "A000055",
    middle_name: "B.",
    most_recent_vote: "2019-11-15",
    propublica_facebook: "RobertAderholt",
    propublica_id: "test_id",
    roles: [
        {
            address: "1203 Longworth House Office Building",
            at_large: false,
            bills_cosponsored: 66,
            bills_sponsored: 1,
            chamber: "House",
            congress: "116",
            contact_form: null,
            district: "4",
            end_date: "2021-01-03",
            fax: null,
            fec_candidate_id: "H6AL04098",
            id: "A000055",
            leadership_role: null,
            level: "federal",
            missed_votes_pct: 1.44,
            ocd_id: "ocd-division/country:us/state:al/cd:4",
            phone: "202-225-4876",
            seniority: "24",
            short_title: "Rep.",
            start_date: "2019-01-03",
            state: "AL",
            stateName: "Alabama",
            status: "won",
            thp_key: null,
            title: "Representative",
            votes_with_party_pct: 92.8,
        }
    ],


    rss_url: "https://aderholt.house.gov/rss.xml",
    twitter_account: "Robert_Aderholt",
    url: "https://aderholt.house.gov",
    votesmart_id: "441",
    youtube_account: "RobertAderholt"
}