name: Node CI

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: |
        npm i
    - name: Test
      run: |
        npm run test
      env:
        TESTING_FIREBASE_TOKEN: {{ secrets.TESTING_FIREBASE_TOKEN }}
        TESTING_PROJECT_ID: {{ secrets.TESTING_PROJECT_ID }}
        TESTING_CLIENT_EMAIL: {{ secrets.TESTING_CLIENT_EMAIL }}
        TESTING_DATABASE_URL: {{ secrets.TESTING_DATABASE_URL }}
        PROPUBLICA: {{ secrets.PROPUBLICA }}
        OPEN_STATES_API_KEY: {{ secrets.OPEN_STATES_API_KEY }}
